#!/usr/bin/env python3
"""Run the third pilot illumination route for TriScope-LLM."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.eval.pilot_illumination import run_pilot_illumination


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Run the materialized third pilot illumination route and optionally extract "
            "illumination features from the resulting raw probe artifacts."
        ),
    )
    parser.add_argument(
        "--experiment-profile",
        default="pilot_csqa_illumination_local",
        help="Experiment profile name inside configs/experiments.yaml.",
    )
    parser.add_argument(
        "--models-config",
        type=Path,
        default=Path("configs/models.yaml"),
        help="Path to the models configuration YAML file.",
    )
    parser.add_argument(
        "--experiments-config",
        type=Path,
        default=Path("configs/experiments.yaml"),
        help="Path to the experiments configuration YAML file.",
    )
    parser.add_argument(
        "--illumination-config",
        type=Path,
        default=Path("configs/illumination.yaml"),
        help="Path to the illumination configuration YAML file.",
    )
    parser.add_argument(
        "--prompt-dir",
        type=Path,
        default=Path("data/prompts/illumination"),
        help="Directory containing illumination prompt templates.",
    )
    parser.add_argument(
        "--materialized-dir",
        type=Path,
        required=True,
        help="Directory containing illumination query contracts generated by materialize_pilot_illumination.py.",
    )
    parser.add_argument("--output-dir", type=Path, required=True, help="Directory where pilot illumination run artifacts will be written.")
    parser.add_argument("--seed", type=int, default=42, help="Deterministic seed for the pilot run.")
    parser.add_argument(
        "--skip-features",
        action="store_true",
        help="Run raw illumination probing only and skip the feature extraction stage.",
    )
    parser.add_argument(
        "--smoke-mode",
        action="store_true",
        help="Clamp budget and generation length for a cheaper pilot execution slice.",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    try:
        result = run_pilot_illumination(
            experiment_profile_name=args.experiment_profile,
            models_config_path=args.models_config,
            experiments_config_path=args.experiments_config,
            illumination_config_path=args.illumination_config,
            prompt_dir=args.prompt_dir,
            materialized_dir=args.materialized_dir,
            output_dir=args.output_dir,
            seed=args.seed,
            extract_features=not args.skip_features,
            smoke_mode=args.smoke_mode,
        )
    except Exception as exc:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        failure_path = args.output_dir / "pilot_illumination_run_failure.json"
        failure_path.write_text(
            json.dumps(
                {
                    "summary_status": "FAIL",
                    "experiment_profile": args.experiment_profile,
                    "materialized_dir": str(args.materialized_dir),
                    "output_dir": str(args.output_dir),
                    "seed": args.seed,
                    "smoke_mode": args.smoke_mode,
                    "error": str(exc),
                },
                indent=2,
                ensure_ascii=True,
            )
            + "\n",
            encoding="utf-8",
        )
        print(f"TriScope-LLM pilot illumination run failed: {exc}")
        print(f"Failure summary: {failure_path.resolve()}")
        return 1

    run_summary = result["run_summary"]
    print("TriScope-LLM pilot illumination run complete")
    print(f"Experiment profile: {run_summary['experiment_profile']}")
    print(f"Feature extraction completed: {run_summary['feature_extraction_completed']}")
    print(f"Run summary: {result['output_paths']['run_summary']}")
    print(f"Config snapshot: {result['output_paths']['config_snapshot']}")
    print(f"Execution log: {result['output_paths']['execution_log']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
